/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Emp;
import Admin.CompanyBrand;
import Admin.vehicle;
import Emp.DriverRecordFileManager;
import com.itextpdf.text.DocumentException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author Abdulkader
 */
public class EmpManage extends javax.swing.JFrame {

    /** Creates new form EmpManage */
    public EmpManage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CusDiag = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        cusID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cusName = new javax.swing.JTextField();
        cusMale = new javax.swing.JRadioButton();
        cusFemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cusAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cusPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cusTaxi = new javax.swing.JRadioButton();
        cusIndividual = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        cusDays = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comBoxName3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cusVeh = new javax.swing.JTextField();
        cusDone = new javax.swing.JButton();
        DriverCheck1 = new javax.swing.JCheckBox();
        jButton8 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        viewCus = new javax.swing.JDialog();
        viewcusID = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        viewcusName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        viewmarkMale = new javax.swing.JRadioButton();
        viewmarkFemale = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        viewcusPhone = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        viewcusAddress = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        viewcusDays = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        viewmarkTaxi = new javax.swing.JRadioButton();
        viewmarkIndividual = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        cusMod = new javax.swing.JButton();
        cusDel = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        viewcusVeh = new javax.swing.JTextField();
        DriverCheckBox2 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        viewcusDriverName = new javax.swing.JTextField();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        viewveh = new javax.swing.JDialog();
        scpane = new javax.swing.JScrollPane();
        empvehtableSearch = new javax.swing.JTable();
        Viewdrive = new javax.swing.JDialog();
        driveaddress1 = new javax.swing.JLabel();
        ViewdriveMale = new javax.swing.JRadioButton();
        viewdriveFemale = new javax.swing.JRadioButton();
        ViewdriveName = new javax.swing.JTextField();
        ViewdriveID = new javax.swing.JTextField();
        ViewdrivePhonenumber = new javax.swing.JTextField();
        drivename1 = new javax.swing.JLabel();
        driveId1 = new javax.swing.JLabel();
        driveGender1 = new javax.swing.JLabel();
        drivePhoto1 = new javax.swing.JLabel();
        experiencedrive = new javax.swing.JLabel();
        viewdriveexperience = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ViewdriveAddress = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        viewdriveday = new javax.swing.JTextField();
        day = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        viewdrivemonth = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        viewdriveyear = new javax.swing.JTextField();
        drivemodify = new javax.swing.JButton();
        drivedelete = new javax.swing.JButton();
        Discard = new javax.swing.JButton();
        DriveDiag = new javax.swing.JDialog();
        drivename = new javax.swing.JLabel();
        driveId = new javax.swing.JLabel();
        driveGender = new javax.swing.JLabel();
        driveaddress = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        markdriveMale = new javax.swing.JRadioButton();
        markdriveFemale = new javax.swing.JRadioButton();
        driveName = new javax.swing.JTextField();
        driveID = new javax.swing.JTextField();
        driveAddress = new javax.swing.JTextField();
        drivePhonenumber = new javax.swing.JTextField();
        driveExperience = new javax.swing.JTextField();
        drivePhoto = new javax.swing.JLabel();
        drivedone = new javax.swing.JButton();
        BirthDate = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        driveday = new javax.swing.JTextField();
        drivemonth = new javax.swing.JTextField();
        driveyear = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        viewDrivers = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        DriverList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        searchCus = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Driversearch = new javax.swing.JButton();
        Searchdrive = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        CusDiag.setTitle("Date");
        CusDiag.setAlwaysOnTop(true);
        CusDiag.setBounds(new java.awt.Rectangle(0, 0, 700, 450));

        jLabel6.setText("Customer ID");

        cusID.setEditable(false);

        jLabel7.setText("Customer Name");

        buttonGroup1.add(cusMale);
        cusMale.setText("Male");

        buttonGroup1.add(cusFemale);
        cusFemale.setText("Female");

        jLabel8.setText("Gender");

        jLabel9.setText("Address");

        jLabel10.setText("Phone Number");

        jLabel11.setText("Customer Using the vehicle as");

        buttonGroup2.add(cusTaxi);
        cusTaxi.setSelected(true);
        cusTaxi.setText("Taxi");

        buttonGroup2.add(cusIndividual);
        cusIndividual.setText("Individual");

        jLabel12.setText("Renting days");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Select the vehicle");

        comBoxName3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Enter Vehicle number");

        cusDone.setText("Done");
        cusDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusDoneActionPerformed(evt);
            }
        });

        DriverCheck1.setText("With Driver ?");

        jButton8.setText("View Available Vehicles");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CusDiagLayout = new javax.swing.GroupLayout(CusDiag.getContentPane());
        CusDiag.getContentPane().setLayout(CusDiagLayout);
        CusDiagLayout.setHorizontalGroup(
            CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CusDiagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cusTaxi)
                    .addGroup(CusDiagLayout.createSequentialGroup()
                        .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CusDiagLayout.createSequentialGroup()
                                .addComponent(cusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(CusDiagLayout.createSequentialGroup()
                                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cusIndividual)
                                    .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cusPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                        .addComponent(cusFemale, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cusMale, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cusID, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cusName, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cusDays, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CusDiagLayout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CusDiagLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DriverCheck1)
                                            .addGroup(CusDiagLayout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(cusDone, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CusDiagLayout.createSequentialGroup()
                                                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(comBoxName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cusVeh, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))))
                .addContainerGap())
        );
        CusDiagLayout.setVerticalGroup(
            CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CusDiagLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CusDiagLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cusMale)
                            .addComponent(DriverCheck1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cusFemale))
                    .addGroup(CusDiagLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)))
                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CusDiagLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10))
                    .addGroup(CusDiagLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cusVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusTaxi)
                    .addComponent(cusIndividual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cusDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CusDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cusDone, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        viewCus.setAlwaysOnTop(true);
        viewCus.setMinimumSize(new java.awt.Dimension(500, 450));

        viewcusID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewcusID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewcusID.setText("Customer ID");

        jLabel17.setText("Customer Name");

        jLabel18.setText("Gender");

        buttonGroup3.add(viewmarkMale);
        viewmarkMale.setText("Male");

        buttonGroup3.add(viewmarkFemale);
        viewmarkFemale.setText("Female");

        jLabel19.setText("Phone Number");

        jLabel20.setText("Address");

        jLabel21.setText("Rented days");

        jLabel22.setText("Vehicle rented as a");

        buttonGroup4.add(viewmarkTaxi);
        viewmarkTaxi.setText("Taxi");

        buttonGroup4.add(viewmarkIndividual);
        viewmarkIndividual.setText("Individual");

        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        cusMod.setText("Modify");
        cusMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusModActionPerformed(evt);
            }
        });

        cusDel.setText("Delete");
        cusDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusDelActionPerformed(evt);
            }
        });

        jLabel14.setText("Car in Use");

        DriverCheckBox2.setText("With Driver");

        jLabel30.setText("Driver Name");

        javax.swing.GroupLayout viewCusLayout = new javax.swing.GroupLayout(viewCus.getContentPane());
        viewCus.getContentPane().setLayout(viewCusLayout);
        viewCusLayout.setHorizontalGroup(
            viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewCusLayout.createSequentialGroup()
                        .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewcusAddress)
                            .addGroup(viewCusLayout.createSequentialGroup()
                                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(viewCusLayout.createSequentialGroup()
                                        .addComponent(viewmarkMale)
                                        .addGap(18, 18, 18)
                                        .addComponent(viewmarkFemale))
                                    .addComponent(viewcusName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewcusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewcusDays, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(viewCusLayout.createSequentialGroup()
                        .addComponent(viewmarkTaxi)
                        .addGap(18, 18, 18)
                        .addComponent(viewmarkIndividual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(cusDel)
                        .addGap(18, 18, 18)
                        .addComponent(cusMod)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(viewCusLayout.createSequentialGroup()
                        .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(viewcusID, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(viewCusLayout.createSequentialGroup()
                                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel30))
                                .addGap(33, 33, 33)
                                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viewcusVeh, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(viewcusDriverName))
                                .addGap(18, 18, 18)
                                .addComponent(DriverCheckBox2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        viewCusLayout.setVerticalGroup(
            viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCusLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(viewcusID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(viewcusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(viewmarkMale)
                    .addComponent(viewmarkFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(viewcusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(viewcusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(viewcusDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewmarkTaxi)
                    .addComponent(viewmarkIndividual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewCusLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(viewcusDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(viewCusLayout.createSequentialGroup()
                        .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewcusVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DriverCheckBox2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(viewCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(cusMod)
                            .addComponent(cusDel))))
                .addContainerGap())
        );

        viewveh.setAlwaysOnTop(true);
        viewveh.setMinimumSize(new java.awt.Dimension(610, 400));

        scpane.setBorder(null);

        empvehtableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        scpane.setViewportView(empvehtableSearch);

        javax.swing.GroupLayout viewvehLayout = new javax.swing.GroupLayout(viewveh.getContentPane());
        viewveh.getContentPane().setLayout(viewvehLayout);
        viewvehLayout.setHorizontalGroup(
            viewvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        viewvehLayout.setVerticalGroup(
            viewvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        Viewdrive.setMinimumSize(new java.awt.Dimension(400, 700));

        driveaddress1.setText("Address");

        buttonGroup5.add(ViewdriveMale);
        ViewdriveMale.setText("Male");

        buttonGroup5.add(viewdriveFemale);
        viewdriveFemale.setText("Female");

        ViewdriveID.setEditable(false);

        ViewdrivePhonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewdrivePhonenumberActionPerformed(evt);
            }
        });

        drivename1.setText("Drivername");

        driveId1.setText("Driver Id");

        driveGender1.setText("Gender");

        drivePhoto1.setBackground(new java.awt.Color(0, 51, 255));

        experiencedrive.setText("Experience");

        jLabel2.setText("Phone number");

        jLabel25.setText("BirthDate");

        viewdriveday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdrivedayActionPerformed(evt);
            }
        });

        day.setText("Day");

        jLabel27.setText("Month");

        jLabel28.setText("Year");

        drivemodify.setText("Modify");
        drivemodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivemodifyActionPerformed(evt);
            }
        });

        drivedelete.setText("Delete");
        drivedelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivedeleteActionPerformed(evt);
            }
        });

        Discard.setText("Cancel");
        Discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewdriveLayout = new javax.swing.GroupLayout(Viewdrive.getContentPane());
        Viewdrive.getContentPane().setLayout(ViewdriveLayout);
        ViewdriveLayout.setHorizontalGroup(
            ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewdriveLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driveId1)
                    .addComponent(drivename1)
                    .addComponent(driveGender1))
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewdriveLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewdriveFemale)
                            .addComponent(ViewdriveMale)))
                    .addGroup(ViewdriveLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ViewdriveID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewdriveLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ViewdriveName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(ViewdriveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewdrivePhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ViewdriveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewdriveLayout.createSequentialGroup()
                        .addComponent(viewdriveday, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewdrivemonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewdriveyear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewdriveLayout.createSequentialGroup()
                        .addComponent(drivemodify)
                        .addGap(18, 18, 18)
                        .addComponent(drivedelete)
                        .addGap(30, 30, 30)
                        .addComponent(Discard))))
            .addGroup(ViewdriveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewdriveLayout.createSequentialGroup()
                        .addComponent(experiencedrive, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(ViewdriveLayout.createSequentialGroup()
                        .addComponent(driveaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGap(2, 2, 2)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewdriveexperience, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewdriveAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewdriveLayout.createSequentialGroup()
                    .addGap(301, 301, 301)
                    .addComponent(drivePhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
        ViewdriveLayout.setVerticalGroup(
            ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewdriveLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drivename1)
                    .addComponent(ViewdriveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driveId1)
                    .addComponent(ViewdriveID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driveGender1)
                    .addComponent(ViewdriveMale))
                .addGap(18, 18, 18)
                .addComponent(viewdriveFemale)
                .addGap(33, 33, 33)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ViewdrivePhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(driveaddress1)
                        .addComponent(ViewdriveAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewdriveLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewdriveexperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(experiencedrive))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewdriveday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewdrivemonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(viewdriveyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drivemodify)
                    .addComponent(drivedelete)
                    .addComponent(Discard))
                .addGap(6, 6, 6))
            .addGroup(ViewdriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewdriveLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(drivePhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
        );

        DriveDiag.setMinimumSize(new java.awt.Dimension(500, 700));

        drivename.setText("Drivername");

        driveId.setText("Driver Id");

        driveGender.setText("Gender");

        driveaddress.setText("Address");

        jLabel26.setText("Experience");

        buttonGroup6.add(markdriveMale);
        markdriveMale.setText("Male");

        buttonGroup6.add(markdriveFemale);
        markdriveFemale.setText("Female");

        driveID.setEditable(false);

        driveAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driveAddressActionPerformed(evt);
            }
        });

        drivePhoto.setBackground(new java.awt.Color(0, 51, 255));

        drivedone.setText("Done");
        drivedone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivedoneActionPerformed(evt);
            }
        });

        BirthDate.setText("BirthDate");

        jLabel16.setText("Day");

        jLabel23.setText("Month");

        jLabel24.setText("Year");

        jLabel29.setText("Phone Number");

        javax.swing.GroupLayout DriveDiagLayout = new javax.swing.GroupLayout(DriveDiag.getContentPane());
        DriveDiag.getContentPane().setLayout(DriveDiagLayout);
        DriveDiagLayout.setHorizontalGroup(
            DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriveDiagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DriveDiagLayout.createSequentialGroup()
                        .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(driveGender)
                            .addComponent(BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driveday, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drivemonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driveyear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(DriveDiagLayout.createSequentialGroup()
                        .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DriveDiagLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(drivedone))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DriveDiagLayout.createSequentialGroup()
                        .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drivename)
                            .addGroup(DriveDiagLayout.createSequentialGroup()
                                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DriveDiagLayout.createSequentialGroup()
                                        .addComponent(driveId)
                                        .addGap(67, 67, 67))
                                    .addGroup(DriveDiagLayout.createSequentialGroup()
                                        .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(driveaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29))
                                        .addGap(54, 54, 54)))
                                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(driveID, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(driveName)
                                        .addComponent(drivePhonenumber)
                                        .addComponent(driveExperience))
                                    .addGroup(DriveDiagLayout.createSequentialGroup()
                                        .addComponent(markdriveMale)
                                        .addGap(44, 44, 44)
                                        .addComponent(markdriveFemale))
                                    .addComponent(driveAddress))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drivePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        DriveDiagLayout.setVerticalGroup(
            DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriveDiagLayout.createSequentialGroup()
                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DriveDiagLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drivename)
                            .addComponent(driveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DriveDiagLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(drivePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driveId)
                    .addComponent(driveID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driveGender)
                    .addComponent(markdriveMale)
                    .addComponent(markdriveFemale))
                .addGap(34, 34, 34)
                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driveaddress)
                    .addComponent(driveAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drivePhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(40, 40, 40)
                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(driveExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DriveDiagLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drivedone))
                    .addGroup(DriveDiagLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(DriveDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driveday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drivemonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driveyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );

        viewDrivers.setMinimumSize(new java.awt.Dimension(600, 400));

        DriverList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(DriverList);

        javax.swing.GroupLayout viewDriversLayout = new javax.swing.GroupLayout(viewDrivers.getContentPane());
        viewDrivers.getContentPane().setLayout(viewDriversLayout);
        viewDriversLayout.setHorizontalGroup(
            viewDriversLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        viewDriversLayout.setVerticalGroup(
            viewDriversLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manage Customers");

        jButton5.setText("Add Customer record");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchCus)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel5)
                    .addComponent(searchCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Drivers");

        jButton1.setText("Add a Driver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Driversearch.setText("Search Driver");
        Driversearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriversearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Driver ID");

        jButton4.setText("View all Drivers");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Driversearch, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Searchdrive, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Driversearch)
                    .addComponent(Searchdrive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DateFormat NewDate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date Date = new Date();
        CustomerRecordFileManager counter=new CustomerRecordFileManager();
        
        cusID.setText(counter.lastId()+"");
        cusName.setText("");
        cusPhone.setText("");
        cusDays.setText("");
        cusAddress.setText("");

        CompanyBrand comname=new CompanyBrand();
        comBoxName3.setModel(comname.getComboModel());

        
      CusDiag.setVisible(true);  
      CusDiag.setTitle(NewDate.format(Date));
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cusDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusDoneActionPerformed
        // TODO add your handling code here:
        
        try{ int CUSID=Integer.parseInt(cusID.getText());
        int PHONENO=Integer.parseInt(cusPhone.getText());
        int NORD=Integer.parseInt(cusDays.getText());
        int vehNum=Integer.parseInt(cusVeh.getText());
        DateFormat NewDate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date Date = new Date();
        String Gender,use;
        if(cusMale.isSelected()) Gender="Male";
        else Gender="Female";
        if(cusTaxi.isSelected()) use="Taxi";
        else use="Individual";    
        boolean driver;
        String dname;
        if(DriverCheck1.isSelected()){
            DriverRecordFileManager Drivername=new DriverRecordFileManager();
         dname=Drivername.returnName();
            driver=true;
        }
        else{
            dname="";
            driver=false;
        }
        int valuetobecalc;
        vehicle k=new vehicle();
        k.setvehicleState(vehNum, true);
        valuetobecalc=k.getvehvalue(vehNum);

        
        
        CustomerRecordFileManager data=new CustomerRecordFileManager();
        CustomerRecord cusData;
        cusData=(new CustomerRecord(CUSID,cusName.getText(),Gender,cusAddress.getText(),PHONENO,use,NORD,vehNum,driver,dname,Date));
        data.addcusRecord(cusData);
                int cusConfirmDiag=JOptionPane.showConfirmDialog(null,"Do u want a pdf file for the record ?", "Warning",JOptionPane.YES_NO_OPTION);
        if(cusConfirmDiag==JOptionPane.YES_OPTION)
        {
           
            PdfManage create=new PdfManage();
                try {
                    String filename=create.pdf(cusData, valuetobecalc);
                    JOptionPane.showMessageDialog(null,"File saved at "+filename);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(EmpManage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DocumentException ex) {
                    Logger.getLogger(EmpManage.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
        
        CusDiag.setVisible(false);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Input Phone Number,vehicle Number and Number Of rent days as integers");
        }

    }//GEN-LAST:event_cusDoneActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DateFormat NewDate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        try{
        int x =Integer.parseInt(searchCus.getText());
        
        CustomerRecordFileManager meh=new CustomerRecordFileManager();
        CustomerRecord cusRead =meh.searchcusRecord(x);
        if(cusRead==null){
            JOptionPane.showMessageDialog(null,"ID not found", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
                viewCus.setVisible(true);
                viewcusID.setText("Customer ID : "+cusRead.ID);
                viewcusName.setText(cusRead.Name);
                if(cusRead.Gender.equals("Male"))viewmarkMale.setSelected(true);
                else viewmarkFemale.setSelected(true);
                viewcusPhone.setText(cusRead.PhoneNum+"");
                viewcusAddress.setText(cusRead.Address);
                viewcusDays.setText(cusRead.NofRentingDays+"");
                if(cusRead.UsedAs.equals("Taxi"))viewmarkTaxi.setSelected(true);
                else viewmarkIndividual.setSelected(true);
                if(cusRead.Driver)DriverCheckBox2.setSelected(true);
                viewcusVeh.setText(cusRead.VehicleNum+"");
                viewcusDriverName.setText(cusRead.DriverName);
                viewCus.setTitle(NewDate.format(cusRead.RentDate)); 
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Input Phone Number and Number Of rent days as integers");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        viewCus.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cusModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusModActionPerformed
        // TODO add your handling code here:
        int cusConfirmDiag=JOptionPane.showConfirmDialog(null,"Are you Show You Want to Modify Customer", "Warning",JOptionPane.YES_NO_OPTION);
        if(cusConfirmDiag==JOptionPane.YES_OPTION)
        {
        try{    Date Date = new Date();
        int x =Integer.parseInt(searchCus.getText());
        int PHONENO=Integer.parseInt(viewcusPhone.getText());
        int NORD=Integer.parseInt(viewcusDays.getText());
        String Gender,state;
        int vehnum=Integer.parseInt(viewcusVeh.getText());
        if(viewmarkMale.isSelected()) Gender="Male";
        else Gender="Female";
        if(viewmarkTaxi.isSelected()) state="Taxi";
        else state="Individual"; 
        boolean driver;
        if(DriverCheckBox2.isSelected())driver=true;
        else driver=false;
        CustomerRecordFileManager cusUpdate=new CustomerRecordFileManager();
        CustomerRecord cusData;
        
        cusData=(new CustomerRecord(x,viewcusName.getText(),Gender,viewcusAddress.getText(),PHONENO,state,NORD,vehnum,driver,viewcusDriverName.getText(),Date));
      cusUpdate.updatecusRecord(x, cusData);
        
            
            viewCus.setVisible(false);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Input Phone Number and Number Of rent days as integers");
        }
        }
    }//GEN-LAST:event_cusModActionPerformed

    private void cusDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusDelActionPerformed
        // TODO add your handling code here:
        int cusConfirmDiag=JOptionPane.showConfirmDialog(null,"Are you Show You Want to Delete Customer", "Warning",JOptionPane.YES_NO_OPTION);
        if(cusConfirmDiag==JOptionPane.YES_OPTION)
        {
         try{   CustomerRecordFileManager del=new CustomerRecordFileManager();
            int x =Integer.parseInt(searchCus.getText());
            del.deletecusRecord(x);
            
            vehicle k=new vehicle();
            int vehNum=Integer.parseInt(viewcusVeh.getText());
            k.setvehicleState(vehNum, false);
            viewCus.setVisible(false);
         }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Input Phone Number and Number Of rent days as integers");
        }
        }
 
    }//GEN-LAST:event_cusDelActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       
        String state;
        if(cusTaxi.isSelected()) state="Taxi";
        else state="Individual"; 
        String[] columnNames={"Brand","Model","Number","Engine Capacity","Sitting Capacity","year",
        "Rent State","Variant","used as","AC","Rent Value"};
        vehicle data=new vehicle();
                String x[][]=data.getTableInfo(comBoxName3.getSelectedItem().toString(),state,false);
        DefaultTableModel model = (DefaultTableModel)empvehtableSearch.getModel();
        model.setColumnIdentifiers(columnNames);
        model.setRowCount(0);
            for (String[] row : x) {
        model.addRow(row);
    }
        
        viewveh.setVisible(true);
        
    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DateFormat NewDate = new SimpleDateFormat("yyyy/MM/dd");
        Date Date = new Date();
        DriverRecordFileManager counter=new DriverRecordFileManager();

        driveID.setText(counter.lastId()+"");
        driveName.setText("");
        drivePhonenumber.setText("");
        driveExperience.setText("");
        driveAddress.setText("");

        DriveDiag.setVisible(true);
        DriveDiag.setTitle(NewDate.format(Date));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DriversearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriversearchActionPerformed

        try{
            int x =Integer.parseInt(Searchdrive.getText());

            DriverRecordFileManager meh=new DriverRecordFileManager();
            DriverRecord driveRead =meh.searchdriveRecord(x);
            if(driveRead==null){
                JOptionPane.showMessageDialog(null,"ID not found", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                Viewdrive.setVisible(true);
                ViewdriveID.setText(driveRead.ID+"");
                ViewdriveName.setText(driveRead.Name);
                if(driveRead.Gender.equals("Male"))ViewdriveMale.setSelected(true);
                else viewdriveFemale.setSelected(true);
                ViewdriveAddress.setText(driveRead.Address);
                ViewdrivePhonenumber.setText(driveRead.PhoneNum+"");
                viewdriveexperience.setText(driveRead.experience+"");
                String[] arr=driveRead.BirthDate.split("/");
                viewdriveday.setText(arr[0]);
                viewdrivemonth.setText(arr[1]);
                viewdriveyear.setText(arr[2]);
                
                
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Input Phone Number and birthdate as integers");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DriversearchActionPerformed

    private void ViewdrivePhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewdrivePhonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewdrivePhonenumberActionPerformed

    private void viewdrivedayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdrivedayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdrivedayActionPerformed

    private void driveAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driveAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driveAddressActionPerformed

    private void drivedoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivedoneActionPerformed
        try{ int driverID=Integer.parseInt(driveID.getText());
            int PHONENO=Integer.parseInt(drivePhonenumber.getText());
            int Expert=Integer.parseInt(driveExperience.getText());
      
            String Gender;
            if(markdriveMale.isSelected()) Gender="Male";
            else Gender="Female";

            String BirthDate=driveday.getText()+"/"+drivemonth.getText()+"/"+driveyear.getText();
            DriverRecordFileManager data=new DriverRecordFileManager();
            DriverRecord driveData=new DriverRecord(driverID,driveName.getText(),Gender,driveAddress.getText(),PHONENO,Expert,BirthDate);
            data.adddriveRecord(driveData);

            DriveDiag.setVisible(false);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Input Phone Number,vehicle Number and Number Of rent days as integers");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_drivedoneActionPerformed

    private void DiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardActionPerformed
        // TODO add your handling code here:
        Viewdrive.setVisible(false);
    }//GEN-LAST:event_DiscardActionPerformed

    private void drivedeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivedeleteActionPerformed
        // TODO add your handling code here:
        int cusConfirmDiag=JOptionPane.showConfirmDialog(null,"Are you Show You Want to Delete Driver", "Warning",JOptionPane.YES_NO_OPTION);
        if(cusConfirmDiag==JOptionPane.YES_OPTION)
        {
            int driverID=Integer.parseInt(ViewdriveID.getText());
          
      
            DriverRecordFileManager data=new DriverRecordFileManager();
            data.deletedriveRecord(driverID);

            Viewdrive.setVisible(false);
        }
    }//GEN-LAST:event_drivedeleteActionPerformed

    private void drivemodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivemodifyActionPerformed
        // TODO add your handling code here:
        int cusConfirmDiag=JOptionPane.showConfirmDialog(null,"Are you Show You Want to Modify driver?", "Warning",JOptionPane.YES_NO_OPTION);
        if(cusConfirmDiag==JOptionPane.YES_OPTION)
        {
                try{ int driverID=Integer.parseInt(ViewdriveID.getText());
            int PHONENO=Integer.parseInt(ViewdriveAddress.getText());
            int Expert=Integer.parseInt(viewdriveexperience.getText());
      
            String Gender;
            if(ViewdriveMale.isSelected()) Gender="Male";
            else Gender="Female";

            String BirthDate=viewdriveday.getText()+"/"+viewdrivemonth.getText()+"/"+viewdriveyear.getText();
            DriverRecordFileManager data=new DriverRecordFileManager();
            DriverRecord driveData=new DriverRecord(driverID,ViewdriveName.getText(),Gender,ViewdrivePhonenumber.getText(),PHONENO,Expert,BirthDate);
            data.updatedriveRecord(driverID, driveData);

            Viewdrive.setVisible(false);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Input Phone Number,vehicle Number and Number Of rent days as integers");
        }
        }
    }//GEN-LAST:event_drivemodifyActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DriverRecordFileManager data=new DriverRecordFileManager();
        ArrayList <DriverRecord> arr=data.arraylistreturn();
        int i =0;
            DefaultTableModel dt = (DefaultTableModel)DriverList.getModel();
            dt.setRowCount(0);
            while(i<arr.size()){
                dt.addRow(new Object[]{arr.get(i).Name,arr.get(i).ID,arr.get(i).Gender,arr.get(i).experience,arr.get(i).PhoneNum,arr.get(i).BirthDate,arr.get(i).Address});
                i++;
            }
            viewDrivers.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpManage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BirthDate;
    private javax.swing.JDialog CusDiag;
    private javax.swing.JButton Discard;
    private javax.swing.JDialog DriveDiag;
    private javax.swing.JCheckBox DriverCheck1;
    private javax.swing.JCheckBox DriverCheckBox2;
    private javax.swing.JTable DriverList;
    private javax.swing.JButton Driversearch;
    private javax.swing.JTextField Searchdrive;
    private javax.swing.JDialog Viewdrive;
    private javax.swing.JTextField ViewdriveAddress;
    private javax.swing.JTextField ViewdriveID;
    private javax.swing.JRadioButton ViewdriveMale;
    private javax.swing.JTextField ViewdriveName;
    private javax.swing.JTextField ViewdrivePhonenumber;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> comBoxName3;
    private javax.swing.JTextField cusAddress;
    private javax.swing.JTextField cusDays;
    private javax.swing.JButton cusDel;
    private javax.swing.JButton cusDone;
    private javax.swing.JRadioButton cusFemale;
    private javax.swing.JTextField cusID;
    private javax.swing.JRadioButton cusIndividual;
    private javax.swing.JRadioButton cusMale;
    private javax.swing.JButton cusMod;
    private javax.swing.JTextField cusName;
    private javax.swing.JTextField cusPhone;
    private javax.swing.JRadioButton cusTaxi;
    private javax.swing.JTextField cusVeh;
    private javax.swing.JLabel day;
    private javax.swing.JTextField driveAddress;
    private javax.swing.JTextField driveExperience;
    private javax.swing.JLabel driveGender;
    private javax.swing.JLabel driveGender1;
    private javax.swing.JTextField driveID;
    private javax.swing.JLabel driveId;
    private javax.swing.JLabel driveId1;
    private javax.swing.JTextField driveName;
    private javax.swing.JTextField drivePhonenumber;
    private javax.swing.JLabel drivePhoto;
    private javax.swing.JLabel drivePhoto1;
    private javax.swing.JLabel driveaddress;
    private javax.swing.JLabel driveaddress1;
    private javax.swing.JTextField driveday;
    private javax.swing.JButton drivedelete;
    private javax.swing.JButton drivedone;
    private javax.swing.JButton drivemodify;
    private javax.swing.JTextField drivemonth;
    private javax.swing.JLabel drivename;
    private javax.swing.JLabel drivename1;
    private javax.swing.JTextField driveyear;
    private javax.swing.JTable empvehtableSearch;
    private javax.swing.JLabel experiencedrive;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton markdriveFemale;
    private javax.swing.JRadioButton markdriveMale;
    private javax.swing.JScrollPane scpane;
    private javax.swing.JTextField searchCus;
    private javax.swing.JDialog viewCus;
    private javax.swing.JDialog viewDrivers;
    private javax.swing.JTextField viewcusAddress;
    private javax.swing.JTextField viewcusDays;
    private javax.swing.JTextField viewcusDriverName;
    private javax.swing.JLabel viewcusID;
    private javax.swing.JTextField viewcusName;
    private javax.swing.JTextField viewcusPhone;
    private javax.swing.JTextField viewcusVeh;
    private javax.swing.JRadioButton viewdriveFemale;
    private javax.swing.JTextField viewdriveday;
    private javax.swing.JTextField viewdriveexperience;
    private javax.swing.JTextField viewdrivemonth;
    private javax.swing.JTextField viewdriveyear;
    private javax.swing.JRadioButton viewmarkFemale;
    private javax.swing.JRadioButton viewmarkIndividual;
    private javax.swing.JRadioButton viewmarkMale;
    private javax.swing.JRadioButton viewmarkTaxi;
    private javax.swing.JDialog viewveh;
    // End of variables declaration//GEN-END:variables

}

