/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdulkader
 */
public class AdminManage extends javax.swing.JFrame {

    /**
     * Creates new form AdminManage
     */
    public AdminManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butgro1 = new javax.swing.ButtonGroup();
        butgro2 = new javax.swing.ButtonGroup();
        vehicleDiagAdd = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        vehModel = new javax.swing.JTextField();
        comBoxName2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        vehNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vehYear = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        vehmarkTaxi = new javax.swing.JRadioButton();
        vehmarkIndividual = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        vehmark4 = new javax.swing.JRadioButton();
        vehmark5 = new javax.swing.JRadioButton();
        vehmark7 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        vehEngine = new javax.swing.JTextField();
        vehmarkAC = new javax.swing.JRadioButton();
        vehmarkNAC = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        vehVerBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        vehRentV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        vehbutDone = new javax.swing.JButton();
        butgro3 = new javax.swing.ButtonGroup();
        butgro4 = new javax.swing.ButtonGroup();
        butgro5 = new javax.swing.ButtonGroup();
        vehicleDiagUpdate = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        vehupModel = new javax.swing.JTextField();
        comBoxName3 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        vehupNum = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        vehupYear = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        vehmarkupTaxi = new javax.swing.JRadioButton();
        vehmarkupIndividual = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        vehmarkup4 = new javax.swing.JRadioButton();
        vehmarkup5 = new javax.swing.JRadioButton();
        vehmarkup7 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        vehupEngine = new javax.swing.JTextField();
        vehmarkupAC = new javax.swing.JRadioButton();
        vehmarkupNAC = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        vehupVar = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        vehupRentV = new javax.swing.JTextField();
        vehupbutCancel = new javax.swing.JButton();
        vehupbutDelete = new javax.swing.JButton();
        vehupbutUpdate = new javax.swing.JButton();
        butgro6 = new javax.swing.ButtonGroup();
        butgro7 = new javax.swing.ButtonGroup();
        butgro8 = new javax.swing.ButtonGroup();
        vehDiagSearch = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehsearchTable = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        gender = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        us = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        quali = new javax.swing.JComboBox<>();
        modify = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        done = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        listDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        addempDiag = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        us1 = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        male1 = new javax.swing.JRadioButton();
        female1 = new javax.swing.JRadioButton();
        quali1 = new javax.swing.JComboBox<>();
        addempCancel = new javax.swing.JButton();
        addempGroup = new javax.swing.ButtonGroup();
        genderadd = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        comName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        comBoxName1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        updatevehNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vehmarkserTaxi = new javax.swing.JRadioButton();
        vehmarkserIndividual = new javax.swing.JRadioButton();
        vehmarkserRented = new javax.swing.JRadioButton();
        vehmarkserUnrented = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addempolyee = new javax.swing.JButton();
        list = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        usern = new javax.swing.JTextField();

        vehicleDiagAdd.setMinimumSize(new java.awt.Dimension(460, 450));

        jLabel6.setText("Car Model");

        comBoxName2.setModel(getComboModel());

        jLabel7.setText("Car Number");

        vehNum.setEditable(false);

        jLabel8.setText("Year");

        jLabel9.setText("Use as ");

        butgro3.add(vehmarkTaxi);
        vehmarkTaxi.setSelected(true);
        vehmarkTaxi.setText("Taxi");

        butgro3.add(vehmarkIndividual);
        vehmarkIndividual.setText("Individual");

        jLabel10.setText("Sitting Capcity");

        butgro4.add(vehmark4);
        vehmark4.setSelected(true);
        vehmark4.setText("4");

        butgro4.add(vehmark5);
        vehmark5.setText("5");

        butgro4.add(vehmark7);
        vehmark7.setText("7");

        jLabel11.setText("Engine Capacity");

        butgro5.add(vehmarkAC);
        vehmarkAC.setSelected(true);
        vehmarkAC.setText("AC");

        butgro5.add(vehmarkNAC);
        vehmarkNAC.setText("Non - Ac");

        jLabel12.setText("Variant");

        vehVerBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top Model", "Economic Model", "Base  Model" }));

        jLabel13.setText("Rent value");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Add Vehicle");

        vehbutDone.setText("Done");
        vehbutDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehbutDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehicleDiagAddLayout = new javax.swing.GroupLayout(vehicleDiagAdd.getContentPane());
        vehicleDiagAdd.getContentPane().setLayout(vehicleDiagAddLayout);
        vehicleDiagAddLayout.setHorizontalGroup(
            vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                        .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                                        .addComponent(vehmark4)
                                        .addGap(18, 18, 18)
                                        .addComponent(vehmark5)
                                        .addGap(18, 18, 18)
                                        .addComponent(vehmark7))
                                    .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                                        .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vehModel)
                                            .addComponent(vehNum)
                                            .addComponent(vehYear, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(comBoxName2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                                        .addComponent(vehmarkTaxi)
                                        .addGap(18, 18, 18)
                                        .addComponent(vehmarkIndividual))))
                            .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                                        .addComponent(vehmarkAC)
                                        .addGap(18, 18, 18)
                                        .addComponent(vehmarkNAC))
                                    .addComponent(vehEngine)
                                    .addComponent(vehVerBox, 0, 134, Short.MAX_VALUE)
                                    .addComponent(vehRentV))))
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vehicleDiagAddLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vehbutDone, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        vehicleDiagAddLayout.setVerticalGroup(
            vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleDiagAddLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vehModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(vehNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vehYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(vehmarkTaxi)
                    .addComponent(vehmarkIndividual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(vehmark4)
                    .addComponent(vehmark5)
                    .addComponent(vehmark7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(vehEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehmarkAC)
                    .addComponent(vehmarkNAC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(vehVerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleDiagAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(vehRentV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehbutDone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vehicleDiagUpdate.setMinimumSize(new java.awt.Dimension(600, 500));

        jLabel15.setText("Vehicle Model");

        comBoxName3.setModel(getComboModel());

        jLabel16.setText("Vehicle Number");

        jLabel17.setText("Year");

        jLabel18.setText("Used as");

        butgro6.add(vehmarkupTaxi);
        vehmarkupTaxi.setText("Taxi");

        butgro6.add(vehmarkupIndividual);
        vehmarkupIndividual.setText("Individual");

        jLabel19.setText("Sitting Capacity");

        butgro7.add(vehmarkup4);
        vehmarkup4.setText("4");

        butgro7.add(vehmarkup5);
        vehmarkup5.setText("5");

        butgro7.add(vehmarkup7);
        vehmarkup7.setText("7");

        jLabel20.setText("Engine Capacity");

        butgro8.add(vehmarkupAC);
        vehmarkupAC.setText("Ac");

        butgro8.add(vehmarkupNAC);
        vehmarkupNAC.setText("Non Ac");

        jLabel21.setText("Vehicle Variant");

        vehupVar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top Model", "Economic Model", "Base Model" }));

        jLabel22.setText("Rent Value");

        vehupbutCancel.setText("Cancel");
        vehupbutCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehupbutCancelActionPerformed(evt);
            }
        });

        vehupbutDelete.setText("Delete");
        vehupbutDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehupbutDeleteActionPerformed(evt);
            }
        });

        vehupbutUpdate.setText("Update");
        vehupbutUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehupbutUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehicleDiagUpdateLayout = new javax.swing.GroupLayout(vehicleDiagUpdate.getContentPane());
        vehicleDiagUpdate.getContentPane().setLayout(vehicleDiagUpdateLayout);
        vehicleDiagUpdateLayout.setHorizontalGroup(
            vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vehicleDiagUpdateLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                                        .addComponent(vehmarkupAC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vehmarkupNAC))
                                    .addComponent(vehupEngine, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vehicleDiagUpdateLayout.createSequentialGroup()
                                .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehupRentV)
                                    .addComponent(vehupVar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(vehupbutUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(vehupbutDelete)
                        .addGap(18, 18, 18)
                        .addComponent(vehupbutCancel))
                    .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                                .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vehupModel)
                                            .addComponent(vehupNum)
                                            .addComponent(vehupYear, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(comBoxName3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                                        .addComponent(vehmarkupTaxi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vehmarkupIndividual))))
                            .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(vehmarkup4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vehmarkup5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vehmarkup7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        vehicleDiagUpdateLayout.setVerticalGroup(
            vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(vehupModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleDiagUpdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(vehupNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(vehupYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(vehmarkupTaxi)
                            .addComponent(vehmarkupIndividual))
                        .addGap(18, 18, 18)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vehmarkup4)
                                .addComponent(vehmarkup5)
                                .addComponent(vehmarkup7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(vehupEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehmarkupAC)
                            .addComponent(vehmarkupNAC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(vehupVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(vehupRentV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vehicleDiagUpdateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                        .addGroup(vehicleDiagUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehupbutCancel)
                            .addComponent(vehupbutDelete)
                            .addComponent(vehupbutUpdate))
                        .addContainerGap())))
        );

        vehDiagSearch.setMinimumSize(new java.awt.Dimension(610, 400));

        vehsearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        jScrollPane1.setViewportView(vehsearchTable);

        javax.swing.GroupLayout vehDiagSearchLayout = new javax.swing.GroupLayout(vehDiagSearch.getContentPane());
        vehDiagSearch.getContentPane().setLayout(vehDiagSearchLayout);
        vehDiagSearchLayout.setHorizontalGroup(
            vehDiagSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehDiagSearchLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        vehDiagSearchLayout.setVerticalGroup(
            vehDiagSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehDiagSearchLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDialog1.setBackground(new java.awt.Color(0, 0, 0));
        jDialog1.setMinimumSize(new java.awt.Dimension(500, 400));
        jDialog1.setSize(new java.awt.Dimension(400, 300));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Name :");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel23.setName("name"); // NOI18N

        jLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("ID :");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel24.setName("name"); // NOI18N

        jLabel25.setBackground(new java.awt.Color(204, 204, 204));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Qualification :");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25.setName("name"); // NOI18N

        jLabel26.setBackground(new java.awt.Color(204, 204, 204));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Gender :");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel26.setName("name"); // NOI18N

        jLabel27.setBackground(new java.awt.Color(204, 204, 204));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Username :");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel27.setName("name"); // NOI18N

        male.setBackground(new java.awt.Color(204, 204, 204));
        genderadd.add(male);
        male.setText("Male");

        female.setBackground(new java.awt.Color(204, 204, 204));
        genderadd.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        quali.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fresh Graduated", "Student", "Proffesional" }));
        quali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualiActionPerformed(evt);
            }
        });

        modify.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modify.setText("Modify");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        done.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name)
                                .addComponent(us)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(female, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                .addComponent(quali, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(male)
                            .addComponent(female))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        listDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        listTable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Gender", "Qualification", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTable.setMinimumSize(new java.awt.Dimension(500, 1500));
        listTable.setPreferredSize(new java.awt.Dimension(300, 400));
        listTable.setRowMargin(0);
        jScrollPane2.setViewportView(listTable);

        javax.swing.GroupLayout listDialogLayout = new javax.swing.GroupLayout(listDialog.getContentPane());
        listDialog.getContentPane().setLayout(listDialogLayout);
        listDialogLayout.setHorizontalGroup(
            listDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        listDialogLayout.setVerticalGroup(
            listDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        addempDiag.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("name");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("password");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("gender");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Qualification");

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Username");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        addempGroup.add(male1);
        male1.setSelected(true);
        male1.setText("Male");

        addempGroup.add(female1);
        female1.setText("Female");
        female1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female1ActionPerformed(evt);
            }
        });

        quali1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fresh Graduated", "Student", "Proffesional" }));
        quali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quali1ActionPerformed(evt);
            }
        });

        addempCancel.setText("Cancel");
        addempCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(male1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(female1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(password)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(us1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(quali1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addempCancel)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(male1)
                        .addComponent(female1))
                    .addComponent(jLabel30))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(quali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(us1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(addempCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addempDiagLayout = new javax.swing.GroupLayout(addempDiag.getContentPane());
        addempDiag.getContentPane().setLayout(addempDiagLayout);
        addempDiagLayout.setHorizontalGroup(
            addempDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addempDiagLayout.setVerticalGroup(
            addempDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Cars and Companies");

        jButton4.setText("Add company");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Add vehicle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        comBoxName1.setModel(getComboModel());

        jButton6.setText("Search vehicle");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Update vehicle");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter vehicle number");

        jLabel4.setText("Company name");

        butgro1.add(vehmarkserTaxi);
        vehmarkserTaxi.setSelected(true);
        vehmarkserTaxi.setText("Taxi");

        butgro1.add(vehmarkserIndividual);
        vehmarkserIndividual.setText("Individual rent");

        butgro2.add(vehmarkserRented);
        vehmarkserRented.setSelected(true);
        vehmarkserRented.setText("Rented");
        vehmarkserRented.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehmarkserRentedActionPerformed(evt);
            }
        });

        butgro2.add(vehmarkserUnrented);
        vehmarkserUnrented.setText("Unrented");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Used as");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(60, 60, 60)
                        .addComponent(comName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(updatevehNum, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comBoxName1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehmarkserIndividual)
                                    .addComponent(vehmarkserTaxi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehmarkserRented)
                                    .addComponent(vehmarkserUnrented))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jLabel3)
                    .addComponent(updatevehNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(comBoxName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehmarkserRented)
                            .addComponent(vehmarkserTaxi))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehmarkserIndividual)
                            .addComponent(vehmarkserUnrented))))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(comName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Employees");

        addempolyee.setText("Add employee");
        addempolyee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempolyeeActionPerformed(evt);
            }
        });

        list.setText("List employees");
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        usern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addempolyee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usern, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(addempolyee)
                .addGap(18, 18, 18)
                .addComponent(list)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usern, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void vehmarkserRentedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehmarkserRentedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehmarkserRentedActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        vehicle newVeh=new vehicle();
        vehNum.setText(newVeh.lastId()+"");
        vehicleDiagAdd.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CompanyBrand comAdd=new CompanyBrand();
        try{
        comAdd.Name=comName.getText();
        comAdd.addCompany(comAdd);
        comBoxName1.setModel(comAdd.getComboModel());
        comBoxName2.setModel(comAdd.getComboModel());
        comBoxName3.setModel(comAdd.getComboModel());
        JOptionPane.showMessageDialog(null, "done");
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void vehbutDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehbutDoneActionPerformed
        // TODO add your handling code here:
        try{
            vehicle newVeh=new vehicle();
            newVeh.brand=comBoxName2.getSelectedItem().toString();
            newVeh.model=vehModel.getText();
            newVeh.variant=vehVerBox.getSelectedItem().toString();
            if(vehmarkTaxi.isSelected())newVeh.use="Taxi";
            else newVeh.use="Individual";
            if(vehmarkAC.isSelected())newVeh.Ac="AC";
            else newVeh.Ac="Non Ac";
            
            newVeh.num=Integer.parseInt(vehNum.getText());
            newVeh.year=Integer.parseInt(vehYear.getText());
            newVeh.engine=Integer.parseInt(vehEngine.getText());
            newVeh.rent_value=Integer.parseInt(vehRentV.getText());
            if(vehmark4.isSelected())newVeh.sitcap=4;
            else if(vehmark5.isSelected())newVeh.sitcap=5;
            else newVeh.sitcap=7;
            newVeh.addvehicle(newVeh);
            JOptionPane.showMessageDialog(null, "done");
            vehicleDiagAdd.setVisible(false);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Enter Integer Values to"
                    + "Vehicle number,year,engine and rent value", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_vehbutDoneActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            vehicle updateVeh=new vehicle();
        int vehNum=Integer.parseInt(updatevehNum.getText());
        updateVeh=updateVeh.searchvehicle(vehNum);
        comBoxName3.setSelectedItem(updateVeh.brand);
        vehupVar.setSelectedItem(updateVeh.variant);
        
        vehupModel.setText(updateVeh.model);
        vehupNum.setText(updateVeh.num+"");
        vehupYear.setText(updateVeh.year+"");
        vehupEngine.setText(updateVeh.engine+"");
        vehupRentV.setText(updateVeh.rent_value+"");
        
        if(updateVeh.use.equals("Taxi"))vehmarkupTaxi.setSelected(true);
        else vehmarkupIndividual.setSelected(true);
        if(updateVeh.sitcap==4)vehmarkup4.setSelected(true);
        else if(updateVeh.sitcap==5)vehmarkup5.setSelected(true);
        else vehmarkup7.setSelected(true);
        if(updateVeh.Ac.equals("AC"))vehmarkupAC.setSelected(true);
        else vehmarkupNAC.setSelected(true);
        
        vehicleDiagUpdate.setVisible(true);
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Enter an integer Value");
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null,"Vehicle Number not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void vehupbutCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehupbutCancelActionPerformed
        // TODO add your handling code here:
        vehicleDiagUpdate.setVisible(false);
    }//GEN-LAST:event_vehupbutCancelActionPerformed

    private void vehupbutUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehupbutUpdateActionPerformed
        // TODO add your handling code here:
            int oldid=Integer.parseInt(updatevehNum.getText());
                try{
            vehicle updateVeh=new vehicle();
            updateVeh.brand=comBoxName3.getSelectedItem().toString();
            updateVeh.model=vehupModel.getText();
            updateVeh.variant=vehupVar.getSelectedItem().toString();
            if(vehmarkupTaxi.isSelected())updateVeh.use="Taxi";
            else updateVeh.use="Individual";
            if(vehmarkupAC.isSelected())updateVeh.Ac="AC";
            else updateVeh.Ac="Non Ac";
            
            updateVeh.num=Integer.parseInt(vehupNum.getText());
            updateVeh.year=Integer.parseInt(vehupYear.getText());
            updateVeh.engine=Integer.parseInt(vehupEngine.getText());
            updateVeh.rent_value=Integer.parseInt(vehupRentV.getText());
            if(vehmarkup4.isSelected())updateVeh.sitcap=4;
            else if(vehmarkup5.isSelected())updateVeh.sitcap=5;
            else updateVeh.sitcap=7;
            
            updateVeh.updatevehicle(oldid, updateVeh);
            JOptionPane.showMessageDialog(null, "done");
            vehicleDiagUpdate.setVisible(false);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Enter Integer Values to"
                    + "Vehicle number,year,engine and rent value", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_vehupbutUpdateActionPerformed

    private void vehupbutDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehupbutDeleteActionPerformed
        // TODO add your handling code here:
        vehicle updateVeh=new vehicle();
        int oldid=Integer.parseInt(updatevehNum.getText());
        updateVeh.deletevehicle(oldid);
        JOptionPane.showMessageDialog(null, "done");
        vehicleDiagUpdate.setVisible(false);
    }//GEN-LAST:event_vehupbutDeleteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        vehicle searchVehs=new vehicle();
        String brand=comBoxName1.getSelectedItem().toString();
        String use;
        if(vehmarkserTaxi.isSelected())use="Taxi";
        else use="Individual";
        boolean state;
        if(vehmarkserRented.isSelected())state=true;
        else state=false;
        String[] columnNames={"Brand","Model","Number","Engine Capacity","Sitting Capacity","year",
        "Rent State","Variant","used as","AC","Rent Value"};
        
        String x[][]=searchVehs.getTableInfo(brand, use, state);
        DefaultTableModel model = (DefaultTableModel)vehsearchTable.getModel();
        model.setColumnIdentifiers(columnNames);
        model.setRowCount(0);
            for (String[] row : x) {
        model.addRow(row);
    }

        vehDiagSearch.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void addempolyeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempolyeeActionPerformed
        // TODO add your handling code here:
        addempDiag.setVisible(true);

    }//GEN-LAST:event_addempolyeeActionPerformed

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        AdminFileManger fm = new AdminFileManger();
        try {
            ArrayList<Employee> arr  = fm.ReadEArray();
            int i =0;
            DefaultTableModel dt = (DefaultTableModel)listTable.getModel();
            dt.setRowCount(0);
            while(i<arr.size()){
                dt.addRow(new Object[]{arr.get(i).name,arr.get(i).id,arr.get(i).gender,arr.get(i).quali,arr.get(i).username});
                i++;
            }
            listDialog.setVisible(true);

        } catch (IOException ex) {
            Logger.getLogger(AdminManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminManage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try {
            // TODO add your handling code here:
            Admin ad = new Admin();
            Employee x=  ad.Search(usern.getText());
            if (x==null){
                JOptionPane.showMessageDialog(null, "This User Does Not Exist","ALERT", JOptionPane.ERROR_MESSAGE);
            }else{
                name.setText(x.name);
                id.setText(Integer.toString(x.id));
                us.setText(x.username);

                if(x.gender.equals("male")){

                    male.setSelected(true);
                    female.setSelected(false);
                }
                else{
                    female.setSelected(true);
                    male.setSelected(false);
                }

                quali.setSelectedItem(x.quali);
                jDialog1.setVisible(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(AdminManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminManage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SearchActionPerformed

    private void usernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernActionPerformed

    private void qualiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualiActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        try {
            Admin x = new Admin();
            Employee e = new Employee();
            e.name = name.getText();
            e.quali = (String) quali.getSelectedItem();
            e.username = us.getText();
            if(male.isSelected()){
                e.gender = "male";
            }
            else{
                e.gender = "female";
            }

            e.id = Integer.parseInt(id.getText());
            if ("".equals(e.name) || "".equals(e.username))
            {
                JOptionPane.showMessageDialog(null, "Please Fill All TextField","ALERT", JOptionPane.ERROR_MESSAGE);
            }else {
                x.modify(Integer.parseInt(id.getText()), e);
                jDialog1.setVisible(false);}
        } catch (IOException ex) {
            Logger.getLogger(AdminManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modifyActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        Admin x = new Admin();
        try {
            x.delete(Integer.parseInt(id.getText()));
            jDialog1.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(AdminManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_doneActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_name1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Employee m=new Employee();
        Admin ad = new Admin();
        m.name =name1.getText();
        m.password = password.getText();
        m.username = us1.getText();
        m.quali = (String) quali1.getSelectedItem();
        if(male1.isSelected()){
            m.gender = "male";
        }
        else{
            m.gender = "female";
        }

        if ("".equals(m.name) || "".equals(m.password) || "".equals(m.username)){
            JOptionPane.showMessageDialog(null, "Please Fill All TextField","ALERT", JOptionPane.ERROR_MESSAGE);
             } else{
            try {
                ad.add(m);
                addempDiag.setVisible(false);
            } catch (IOException ex) {
                
            } catch (ClassNotFoundException ex) {

            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void female1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female1ActionPerformed

    private void quali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quali1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quali1ActionPerformed

    private void addempCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempCancelActionPerformed
        // TODO add your handling code here:
        addempDiag.setVisible(false);
    }//GEN-LAST:event_addempCancelActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed
public ComboBoxModel getComboModel ()
{
    CompanyBrand gtc=new CompanyBrand();
  return new  DefaultComboBoxModel (gtc.convertToArray());
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton add;
    private javax.swing.JButton addempCancel;
    private javax.swing.JDialog addempDiag;
    private javax.swing.ButtonGroup addempGroup;
    private javax.swing.JButton addempolyee;
    private javax.swing.ButtonGroup butgro1;
    private javax.swing.ButtonGroup butgro2;
    private javax.swing.ButtonGroup butgro3;
    private javax.swing.ButtonGroup butgro4;
    private javax.swing.ButtonGroup butgro5;
    private javax.swing.ButtonGroup butgro6;
    private javax.swing.ButtonGroup butgro7;
    private javax.swing.ButtonGroup butgro8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comBoxName1;
    private javax.swing.JComboBox<String> comBoxName2;
    private javax.swing.JComboBox<String> comBoxName3;
    private javax.swing.JTextField comName;
    private javax.swing.JButton delete;
    private javax.swing.JButton done;
    private javax.swing.JRadioButton female;
    private javax.swing.JRadioButton female1;
    private javax.swing.ButtonGroup gender;
    private javax.swing.ButtonGroup genderadd;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton list;
    private javax.swing.JDialog listDialog;
    private javax.swing.JTable listTable;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton male1;
    private javax.swing.JButton modify;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> quali;
    private javax.swing.JComboBox<String> quali1;
    private javax.swing.JTextField updatevehNum;
    private javax.swing.JTextField us;
    private javax.swing.JTextField us1;
    private javax.swing.JTextField usern;
    private javax.swing.JDialog vehDiagSearch;
    private javax.swing.JTextField vehEngine;
    private javax.swing.JTextField vehModel;
    private javax.swing.JTextField vehNum;
    private javax.swing.JTextField vehRentV;
    private javax.swing.JComboBox<String> vehVerBox;
    private javax.swing.JTextField vehYear;
    private javax.swing.JButton vehbutDone;
    private javax.swing.JDialog vehicleDiagAdd;
    private javax.swing.JDialog vehicleDiagUpdate;
    private javax.swing.JRadioButton vehmark4;
    private javax.swing.JRadioButton vehmark5;
    private javax.swing.JRadioButton vehmark7;
    private javax.swing.JRadioButton vehmarkAC;
    private javax.swing.JRadioButton vehmarkIndividual;
    private javax.swing.JRadioButton vehmarkNAC;
    private javax.swing.JRadioButton vehmarkTaxi;
    private javax.swing.JRadioButton vehmarkserIndividual;
    private javax.swing.JRadioButton vehmarkserRented;
    private javax.swing.JRadioButton vehmarkserTaxi;
    private javax.swing.JRadioButton vehmarkserUnrented;
    private javax.swing.JRadioButton vehmarkup4;
    private javax.swing.JRadioButton vehmarkup5;
    private javax.swing.JRadioButton vehmarkup7;
    private javax.swing.JRadioButton vehmarkupAC;
    private javax.swing.JRadioButton vehmarkupIndividual;
    private javax.swing.JRadioButton vehmarkupNAC;
    private javax.swing.JRadioButton vehmarkupTaxi;
    private javax.swing.JTable vehsearchTable;
    private javax.swing.JTextField vehupEngine;
    private javax.swing.JTextField vehupModel;
    private javax.swing.JTextField vehupNum;
    private javax.swing.JTextField vehupRentV;
    private javax.swing.JComboBox<String> vehupVar;
    private javax.swing.JTextField vehupYear;
    private javax.swing.JButton vehupbutCancel;
    private javax.swing.JButton vehupbutDelete;
    private javax.swing.JButton vehupbutUpdate;
    // End of variables declaration//GEN-END:variables
}
